FROM mysql:8.0	
COPY ./my.cnf /etc/mysql
#RUN mysql -ubbdd_user -pbolson --reconnect -e "CREATE DATABASE bbdd_user CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
#RUN echo "default-storage-engine=INNODB" >> /etc/mysql/my.cnf
#RUN echo "character-set-server=utf8mb4" >> /etc/mysql/my.cnf
#RUN echo "collation-server=utf8mb4_bin" >> /etc/mysql/my.cnf
#RUN echo "max_allowed_packet=256M" >> /etc/mysql/my.cnf
#RUN echo "innodb_default_row_format=DYNAMIC" >> /etc/mysql/my.cnf
#RUN echo "innodb_large_prefix=ON" >> /etc/mysql/my.cnf
#RUN echo "innodb_file_format=Barracuda" >> /etc/mysql/my.cnf
#RUN echo "innodb_log_file_size=2G" >> /etc/mysql/my.cnf
#RUN echo "transaction-isolation=READ-COMMITTED" >> /etc/mysql/my.cnf
#RUN echo "binlog_format=ro" >> /etc/mysql/my.cnf
#RUN echo "log_bin_trust_function_creators = 1" >> /etc/mysql/my.cnf
